#pragma once

#define SPLIT_LAYER_STATE_ENABLE

#ifdef RGB_MATRIX_ENABLE
#    define SPLIT_LED_STATE_ENABLE
#    undef RGB_MATRIX_DEFAULT_MODE
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#endif

#define MK_KINETIC_SPEED
// #undef MOUSEKEY_DELAY
// #define MOUSEKEY_DELAY 5

// #undef MOUSEKEY_INTERVAL
// #define MOUSEKEY_INTERVAL 10

// #undef MOUSEKEY_MOVE_DELTA
// #define MOUSEKEY_MOVE_DELTA 25

// #undef MOUSEKEY_INITIAL_SPEED
// #define MOUSEKEY_INITIAL_SPEED 100

#undef MOUSEKEY_BASE_SPEED
#define MOUSEKEY_BASE_SPEED 6000
